### ISSUE TITLE
Style issues on Meta

### ISSUE THREAD

**Issue by melhosseiny** [melhosseiny/ghost#1]
User panel buttons have a grey background, and menu items have wrong colors on hover 👍🏻

<img width="346" alt="Screenshot 2021-10-09 at 14 07 06" src="https://user-images.githubusercontent.com/3174355/136657207-47221311-93e1-4bca-948a-212a55e0e807.png">

<img width="343" alt="Screenshot 2021-10-09 at 14 08 39" src="https://user-images.githubusercontent.com/3174355/136657261-66608a3c-b48b-4eb0-85c3-12b39652f395.png">

Wrong background color after hovering an item then moving off the category chooser 👍🏻

<img width="232" alt="Screenshot 2021-10-09 at 14 12 13" src="https://user-images.githubusercontent.com/3174355/136657420-7ee9f9e7-6594-4b58-8c19-ca73bc02b6f0.png">

Misaligned label and arrow in period chooser 👍🏻 

<img width="258" alt="Screenshot 2021-10-09 at 14 19 35" src="https://user-images.githubusercontent.com/3174355/136657611-bfabfbb6-881b-40d2-8bdc-5441f4c77206.png">

Remove topic timer info border 👍🏻 

<img width="790" alt="Screenshot 2021-10-09 at 18 29 17" src="https://user-images.githubusercontent.com/3174355/136666684-40f234ef-70ff-4565-bc8a-bf874cb9e01c.png">

Like icon is grey sometimes 🙈 

<img width="306" alt="Screenshot 2021-10-09 at 14 33 09" src="https://user-images.githubusercontent.com/3174355/136658044-93a8920e-51e5-4fdf-9b7b-1663cf472c27.png">

New search page lost cyberpunk gradient 👍🏻 

<img width="1125" alt="Screenshot 2021-10-09 at 14 25 50" src="https://user-images.githubusercontent.com/3174355/136657803-6200b989-08d6-4c09-8d07-472320eec427.png">

Categories in categories page have extra margin on top 👍🏻 

<img width="691" alt="Screenshot 2021-10-09 at 14 17 55" src="https://user-images.githubusercontent.com/3174355/136657558-32d4deda-b865-468a-89e0-8527734274ce.png">

Style docs plugin page 👍🏻 

<img width="1131" alt="Screenshot 2021-10-09 at 14 22 41" src="https://user-images.githubusercontent.com/3174355/136657662-03cc9aa3-6832-4a0a-a9e2-699977d79417.png">

New topic notification badge is misplaced, and showing a black square 👍🏻 

<img width="346" alt="Screenshot 2021-10-09 at 14 04 44" src="https://user-images.githubusercontent.com/3174355/136657140-60c9b5ef-a155-496f-9215-aea0fb78aa32.png">

Rounded corners in message threads need restyling 👍🏻 

<img width="789" alt="Screenshot 2021-10-09 at 14 30 24" src="https://user-images.githubusercontent.com/3174355/136657985-dc94fb03-f609-43fa-92f5-5009a93f5c8a.png">

New search dropdown has some misalignments and wrong colors when hovering items 👍🏻 

<img width="530" alt="Screenshot 2021-10-09 at 14 24 06" src="https://user-images.githubusercontent.com/3174355/136657748-136412c3-a75e-4c93-a230-5a3e787c456d.png">

Topic last visit separator needs restyling

<img width="789" alt="Screenshot 2021-10-09 at 18 32 40" src="https://user-images.githubusercontent.com/3174355/136666798-6ea6e392-db2e-41af-944a-d8d1333b8825.png">

Composer inputs have different heights 👍🏻 

<img width="571" alt="Screenshot 2021-10-09 at 14 16 08" src="https://user-images.githubusercontent.com/3174355/136657495-673b145e-0945-4ee0-a495-6ba24108c887.png">

Posts filtered notice width is not correct 👍🏻 

<img width="799" alt="Screenshot 2021-10-09 at 18 25 28" src="https://user-images.githubusercontent.com/3174355/136666575-fb38b701-ce5d-43b2-a17a-dc17d5954fcf.png">

Lazy loading in topic page needs restyling 👍🏻 

<img width="797" alt="Screenshot 2021-10-09 at 18 36 51" src="https://user-images.githubusercontent.com/3174355/136666892-f814d7c5-15a0-4fac-b4fc-3d601a66d181.png">

```
<div id="ember2943" class="loading-container visible ember-view">
  <article class="placeholder">
    <div class="row" style="">
      <div class="topic-avatar">
        <div class="placeholder-avatar placeholder-animation"></div>
      </div>
      <div class="topic-body">
        <div class="placeholder-text placeholder-animation"></div>
        <div class="placeholder-text placeholder-animation"></div>
        <div class="placeholder-text placeholder-animation"></div>
      </div>
    </div>
  </article>
  <article class="placeholder">
    <div class="row" style="">
      <div class="topic-avatar">
        <div class="placeholder-avatar placeholder-animation"></div>
      </div>
      <div class="topic-body">
        <div class="placeholder-text placeholder-animation"></div>
        <div class="placeholder-text placeholder-animation"></div>
        <div class="placeholder-text placeholder-animation"></div>
      </div>
    </div>
  </article>
</div>
```

Unread posts count could look better :+1:

<img width="395" alt="Screenshot 2021-10-09 at 23 04 41" src="https://user-images.githubusercontent.com/3174355/136673790-07599f13-11f1-41eb-ad50-4f4f9523c7fe.png">

```
<span class="topic-post-badges">
    &nbsp;<a href="{{url}}" class="badge badge-notification unread-posts" title="{{i18n &quot;topic.unread_posts&quot; count=newPosts}}">23</a>
    &nbsp;<a href="{{url}}" class="badge badge-notification unread-posts" title="{{i18n &quot;topic.unread_posts&quot; count=unreadPosts}}">7</a>
    &nbsp;<a href="{{url}}" class="badge badge-notification new-topic" title="{{i18n &quot;topic.new&quot;}}">new</a>
</span>
```

**Theme maintenance**

- [x] Remove autoprefixed rules
- [x] Move SCSS variables out of common
- [x] Use CSS variables when possible
- [x] Match discourse source order
